<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>net.luversof</groupId>
		<artifactId>bluesky-web</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<artifactId>bluesky-web-user</artifactId>
	<name>bluesky-web-user</name>
	<description>bluesky-web-user</description>
	<dependencies>
		<!-- (s) spring-boot -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-oauth2-client</artifactId>
		</dependency>
		<!-- (e) spring-boot -->

		<!-- (s) spring-boot-admin -->
		<dependency>
			<groupId>de.codecentric</groupId>
			<artifactId>spring-boot-admin-starter-client</artifactId>
		</dependency>
		<!-- (e) spring-boot-admin -->

		<!-- (s) bluesky -->
		<dependency>
			<groupId>net.luversof</groupId>
			<artifactId>bluesky-client-user</artifactId>
		</dependency>
		<dependency>
			<groupId>net.luversof</groupId>
			<artifactId>bluesky-web-common</artifactId>
		</dependency>
		<!-- (e) bluesky -->
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>com.google.cloud.tools</groupId>
				<artifactId>jib-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>