


bluesky-boot.connection-info.mongodb.connection-map.test1.hosts=localhost:27017
bluesky-boot.connection-info.mongodb.connection-map.test1.database=mongoTest
#bluesky-boot.connection-info.mongodb.connection-map.test1.username=
#bluesky-boot.connection-info.mongodb.connection-map.test1.password=


bluesky-boot.connection-info.readers.properties-mongoclient.enabled=true
bluesky-boot.connection-info.loaders.mongoclient.enabled=true
bluesky-boot.connection-info.loaders.mongoclient.connections.test=test1
