DROP DATABASE IF EXISTS user;
DROP DATABASE IF EXISTS blog;
DROP DATABASE IF EXISTS bookkeeping;
DROP DATABASE IF EXISTS bbs;

CREATE DATABASE IF NOT EXISTS user;
CREATE DATABASE IF NOT EXISTS blog;
CREATE DATABASE IF NOT EXISTS bookkeeping;
CREATE DATABASE IF NOT EXISTS bbs;