server:
  port: 8082
spring:
  application:
    name: bluesky-web-default
  messages.basename: classpath:static/message/message
  web.locale: KO_KR
  mvc:
    contentnegotiation:
      media-types:
        json: application/json
  jackson:
    serialization:
      write-dates-as-timestamps: false