server:
  port: 8082
spring:
  application:
    name: bluesky-project
  messages.basename: classpath:static/message/message
  web.locale: KO_KR
  mvc:
    contentnegotiation:
      media-types:
        json: application/json
  jackson:
    serialization:
      write-dates-as-timestamps: false
  config.import: classpath:/config/bootstrap.yml
---
spring:
  config:
    activate.on-profile: localdev
    import: configserver:http://localhost:8888
  cloud:
    config:
      profile: localdev
---