server.port=30121
spring.application.name=bluesky-web-default

spring.config.import=https://raw.githubusercontent.com/luversof/bluesky-config-repo/develop/bootstrap_v2.4.yml
spring.cloud.config.name=bluesky-project

theme-list=default,cerulean,cosmo,cyborg,darkly,flatly,journal,litera,lumen,lux,materia,minty,pulse,sandstone,simplex,sketchy,slate,solar,spacelab,superhero,united,yeti

bluesky-boot.dev-check.base-packages=net.luversof


spring.mvc.hiddenmethod.filter.enabled=true

#---
spring.config.activate.on-profile=localdev
#spring.config.import=configserver:,https://raw.githubusercontent.com/luversof/bluesky-config-repo/refs/heads/develop/test.properties
spring.config.import=configserver:,optional:https://dev.bluesky.local:40122/test.properties
#spring.config.import=configserver:,optional:configserver:https://dev.bluesky.local:40101
server.port=40121

spring.messages.cache-duration=5
spring.thymeleaf.cache=false
# spring.boot.admin.client.enabled=false
debug=true

# (s) bluesky-module test
bluesky-boot.core.module-name-set=a, b
# bluesky-boot.locale.modules.a.enable-locale-list=en_US
bluesky-boot.external-locale.modules.b.enable-locale-list=en_US
# (e) bluesky-module test


#---
spring.config.activate.on-profile=opdev
spring.config.import=configserver:

debug=true
spring.graphql.schema.printer.enabled=true
spring.graphql.graphiql.enabled=true

#---
spring.config.activate.on-profile=k8sdev
spring.config.import=configserver: