# connection-info
bluesky-boot.connection-info.readers.postgresql-datasource.enabled=true
bluesky-boot.connection-info.loaders.hikaridatasource.enabled=true
bluesky-boot.connection-info.loaders.hikaridatasource.connections.google_api=google_api_postgresql
