package net.luversof.blog.constant;

public enum BlogErrorCode {
	NOT_USER_BLOG,
	NOT_USER_BLOGARTICLE,
	NOT_USER_BLOGARTICLECATEGORY,
	
	NOT_EXIST_USER_BLOG,
	ALREADY_EXIST_USER_BLOG,
	
	NOT_EXIST_BLOG,
	NOT_EXIST_BLOGARTICLE,
	
	NOT_EXIST_BLOGARTICLECATEGORY,
	
	NOT_EXIST_PARAMETER_BLOG_ID,
	
	INVALID_PARAMETER_BLOG_ID,
	INVALID_PARAMETER_BLOGARTICLE_ID,
	INVALID_PARAMETER_BLOGCATEGORY_ID
}
