package net.luversof.blog.constant;

public enum BlogErrorCode {
	NOT_EXIST_USER_ID,
	
	NOT_EXIST_BLOG,
	NOT_EXIST_ARTICLE,
	
	NOT_USER_BLOG,
	NOT_EXIST_USER_BLOG,
	ALREADY_EXIST_USER_BLOG,
	
	NOT_EXIST_PARAMETER_BLOG_ID,
	INVALID_PARAMETER_BLOG_ID,
	INVALID_PARAMETER_ARTICLE_ID,
	;
}
