server.servlet.session.timeout=365d
server.servlet.session.cookie.name=BLUESKY_SESSION
server.servlet.session.cookie.domain=bluesky.local
server.servlet.session.cookie.max-age=365d
spring.session.timeout=365d
