<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>net.luversof</groupId>
		<artifactId>bluesky-web</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<artifactId>bluesky-web-dynamiccrud</artifactId>

	<dependencies>
		<!-- (s) spring-boot -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-mongodb</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<!-- (e) spring-boot -->
		
		<!-- (s) springdoc-openapi -->
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
		</dependency>
		<!-- (e) springdoc-openapi -->
		
		<!-- (e) bluesky boot connectioninfo -->
		<dependency>
			<groupId>io.github.luversof</groupId>
			<artifactId>bluesky-boot-autoconfigure-connectioninfo-jdbc</artifactId>
		</dependency>
		<dependency>
			<groupId>io.github.luversof</groupId>
			<artifactId>bluesky-boot-autoconfigure-connectioninfo-mongodb</artifactId>
		</dependency>
		<!-- (e) bluesky boot connectioninfo -->
		
		<!-- (s) bluesky boot crypto -->
		<dependency>
			<groupId>io.github.luversof</groupId>
			<artifactId>bluesky-boot-crypto</artifactId>
		</dependency>
		<!-- (e) bluesky boot crypto -->
		
		<!-- (e) bluesky boot devcheck-->
		<dependency>
			<groupId>io.github.luversof</groupId>
			<artifactId>bluesky-boot-autoconfigure-devcheck</artifactId>
		</dependency>
		<!-- (e) bluesky boot devcheck-->

		<!-- (s) jdbc -->
		<dependency>
			<groupId>com.microsoft.sqlserver</groupId>
			<artifactId>mssql-jdbc</artifactId>
		</dependency>
		<dependency>
			<groupId>org.mariadb.jdbc</groupId>
			<artifactId>mariadb-java-client</artifactId>
		</dependency>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
		</dependency>
		<!-- (e) jdbc -->
		
		<!-- (s) jte -->
		<dependency>
						<groupId>gg.jte</groupId>
						<artifactId>jte-spring-boot-starter-3</artifactId>
						<version>3.1.12</version>
				</dependency>
				<dependency>
						<groupId>gg.jte</groupId>
						<artifactId>jte-models</artifactId>
						<version>3.1.12</version>
				</dependency>
				<!-- (e) jte -->

		<!-- (s) poi -->
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
		</dependency>
		<!-- (e) poi -->
		
		<dependency>
			<groupId>com.github.jsqlparser</groupId>
			<artifactId>jsqlparser</artifactId>
		</dependency>
		
		<!-- (s) webjars -->
		<dependency>
			<groupId>org.webjars</groupId>
			<artifactId>webjars-locator-lite</artifactId>
		</dependency>
		<dependency>
			<groupId>org.webjars.npm</groupId>
			<artifactId>theme-change</artifactId>
			<version>2.5.0</version>
		</dependency>
		<dependency>
			<groupId>org.webjars.npm</groupId>
			<artifactId>htmx.org</artifactId>
			<version>2.0.4</version>
		</dependency>
		<!-- (e) webjars -->
		
		<!-- (s) bluesky -->
		<dependency>
			<groupId>net.luversof</groupId>
			<artifactId>bluesky-client-user</artifactId>
		</dependency>
		<dependency>
			<groupId>net.luversof</groupId>
			<artifactId>bluesky-web-common</artifactId>
		</dependency>
		<!-- (e) bluesky -->

	</dependencies>

	<build>
		<plugins>
			<!--<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>3.1.0</version>
				<executions>
					<execution>
						<id>exec-npm-build</id>
						<phase>generate-sources</phase>

						<goals>
							<goal>exec</goal>
						</goals>

						<configuration>
							<executable>npm</executable>
							<arguments>
								<argument>run</argument>
								<argument>build</argument>
							</arguments>
							<workingDirectory>${basedir}/src/main/frontend</workingDirectory>
							<async>true</async>
						</configuration>

					</execution>
				</executions>
			</plugin>-->

			<plugin>
				<groupId>gg.jte</groupId>
				<artifactId>jte-maven-plugin</artifactId>
				<version>3.1.12</version>
				<executions>
					<execution>
						<id>jte-generate</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<sourceDirectory>${project.basedir}/src/main/jte</sourceDirectory>
							<contentType>Html</contentType>
							<binaryStaticContent>true</binaryStaticContent>
							<targetResourceDirectory>${project.build.directory}/generated-sources/jte</targetResourceDirectory>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>add-resource</id>
						<phase>generate-resources</phase>
						<goals>
							<goal>add-resource</goal>
						</goals>
						<configuration>
							<resources>
								<resource>
									<directory>
										${project.build.directory}/generated-sources/jte</directory>
								</resource>
							</resources>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>com.google.cloud.tools</groupId>
				<artifactId>jib-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>