server.port=30133
spring.application.name=bluesky-api-board
spring.config.import=https://raw.githubusercontent.com/luversof/bluesky-config-repo/develop/bootstrap_v2.4.yml

spring.cloud.config.name=bluesky-project

bluesky-boot.message-source.board=classpath:boardMessage

#datasource.board.username=${datasource.default.username}
#datasource.board.password=${datasource.default.password}
#datasource.board.type=${datasource.default.type}
#datasource.board.url=${datasource.default.url}/board?useSSL=false&useUnicode=true&autoReconnection=true

#bluesky-boot.connection-info.readers.mariadb-datasource.enabled=true
bluesky-boot.connection-info.readers.postgresql-datasource.enabled=true
bluesky-boot.connection-info.loaders.hikaridatasource.enabled=true
bluesky-boot.connection-info.loaders.hikaridatasource.connections.mapexample=board_postgresql

#bluesky-boot.datasource.enabled=true
#bluesky-boot.datasource.default-datasource=board

#spring.jpa.properties.hibernate.connection.handling_mode=DELAYED_ACQUISITION_AND_RELEASE_AFTER_STATEMENT


bluesky-boot.dev-check.base-package-list=net.luversof,io.github.luversof.boot

#---
spring.config.activate.on-profile=localdev | opdev
spring.config.import=configserver:
server.port=40133

debug=true

#---
spring.config.activate.on-profile=k8sdev
spring.config.import=configserver:

