package net.luversof.bookkeeping.constant;

public enum BookkeepingErrorCode {
	NOT_EXIST_BOOKKEEPING,
	NOT_EXIST_ASSET,
	NOT_EXIST_ENTRYGROUP,
	NOT_EXIST_ENTRY,
	NOT_EXIST_USER_ID,

	NOT_OWNER_BOOKKEEPING,
	NOT_OWNER_ASSET,
	NOT_OWNER_ENTRYGROUP,
	NOT_OWNER_ENTRY,
	
	NOT_SUPPORT_CHRONOUNIT,
	;
}
