server.port=30131
spring.application.name=bluesky-api-user
spring.config.import=https://raw.githubusercontent.com/luversof/bluesky-config-repo/develop/bootstrap_v2.4.yml

spring.cloud.config.name=bluesky-project

bluesky-boot.connection-info.readers.postgresql-datasource.enabled=true
bluesky-boot.connection-info.loaders.hikaridatasource.enabled=true
bluesky-boot.connection-info.loaders.hikaridatasource.connections.stock=user_postgresql

#---
spring.config.activate.on-profile=localdev | opdev
server.port=40131
spring.config.import=configserver:

debug=true


#---
spring.config.activate.on-profile=k8sdev
spring.config.import=configserver:

