server.port=30134
spring.application.name=bluesky-api-stock
#spring.config.import=https://raw.githubusercontent.com/luversof/bluesky-config-repo/develop/bootstrap_v2.4.yml
spring.config.import=classpath:/bootstrap.yml

spring.cloud.config.name=bluesky-project

# OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://user.api.bluesky.local:30131
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://user.api.bluesky.local:30131/oauth2/jwks

bluesky-boot.message-source.bookkeeping=classpath:stockMessage

bluesky-boot.connection-info.readers.postgresql-datasource.enabled=true
bluesky-boot.connection-info.loaders.hikaridatasource.enabled=true
bluesky-boot.connection-info.loaders.hikaridatasource.connections.stock=stock_postgresql

#---
spring.config.activate.on-profile=localdev | opdev
spring.config.import=configserver:
server.port=40134

# OAuth2 Resource Server (localdev/opdev)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev.bluesky.local:40131
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://dev.bluesky.local:40131/oauth2/jwks

debug=true

#---
spring.config.activate.on-profile=k8sdev
spring.config.import=configserver:


