server.port=30124
spring.application.name=bluesky-web-user
spring.config.import=https://raw.githubusercontent.com/luversof/bluesky-config-repo/develop/bootstrap_v2.4.yml
spring.cloud.config.name=bluesky-project
spring.session.data.redis.namespace=spring:session:bluesky
spring.data.redis.host=redis.bluesky.local
server.forward-headers-strategy=framework

#---
spring.config.activate.on-profile=k8sdev
spring.config.import=configserver:
spring.http.serviceclient.client-user.base-url=lb://bluesky-api-user


#---
spring.config.activate.on-profile=localdev | opdev
server.port=40124
spring.config.import=configserver:


spring.http.serviceclient.client-user.base-url=https://user.api.bluesky.local
