package net.luversof.core.exception;

public enum ErrorCode {

	NOT_EXIST_USER,
	NOT_EXIST_USER_FACEBOOK,
	NOT_EXIST_USER_GITHUB,
	NOT_EXIST_USER_BATTLENET,
	
	NOT_EXIST_BLOG,
	
	NOT_EXIST_BOOKKEEPING
}
